modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="algotech"
version="${file.jarVersion}"
displayName="AlgoTech"
authors="AlgortihmLX"
description='''

'''
[[dependencies.algotech]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.algotech]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"